#! /usr/bin/ruby
require_relative './bank'

def ask question
  print "#{question} "
  gets.strip
end

def prompt_for_transactions(bank)
  prompt = "What do you want to do (Add|Credit|Charge|Quit)?"
  until ((txn = ask prompt) =~ /^q/i)
    process_transaction bank, txn
  end
end

def process_transaction(bank, transaction)
  (action, name, num1, num2) = transaction.split
  case action
  when /Add/i
    card = CreditCard.new(num1.to_i, dollar_value(num2))
    bank.add_account name, card
  when /Credit/i
    bank.credit_account name, dollar_value(num1)
  when /Charge/i
    bank.charge_account name, dollar_value(num1)
  end
end

def dollar_value string
  string =~ /^\$?(\d*)$/
  $1.to_i
end

bank = Bank.new
if ARGV[0] && File.exists?(ARGV[0])
  file = File.new(ARGV[0])
  file.each do |txn|
    process_transaction bank, txn
  end
else
  prompt_for_transactions bank
end

puts bank.accounts
